steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nifty-catfish-458019-a0/spotipunk-image:$COMMIT_SHA', '.']

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nifty-catfish-458019-a0/spotipunk-image:$COMMIT_SHA']

  # Step 3: Update the Cloud Run Job to use the new image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - 'run'
      - 'jobs'
      - 'update'
      - 'spotipunk-pipeline'
      - '--image'
      - 'gcr.io/nifty-catfish-458019-a0/spotipunk-image:$COMMIT_SHA'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/nifty-catfish-458019-a0/spotipunk-image:$COMMIT_SHA'